/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ProcessInfo {
  pid: number
  parentPid?: number
  name: string
  exe?: string
  cmd: string[]
  cwd?: string
  /** Epoch seconds for diagnostics; not a unique process identity. */
  startTime: bigint
}

/** Read-only snapshot. Overlapping calls share a scan; each caller has its own 1..30000 ms budget.
 * Rejects with ERR_PROCESS_QUERY_TIMEOUT or ERR_PROCESS_QUERY_INVALID_TIMEOUT.
 * Waiting can time out while OS enumeration continues; no completed snapshot is cached. */
export declare function queryProcesses(timeoutMs: number): Promise<ProcessInfo[]>

export declare class Cpu {
  usage(): number
  name(): string
  name(): string
  /** Cpu frequency in `MHz` */
  frequency(): number
  vendorId(): string
  brand(): string
}

export declare class SysInfo {
  constructor()
  cpus(): Array<Cpu>
  refreshMemory(): void
  totalMemory(): bigint
  freeMemory(): bigint
  availableMemory(): bigint
  usedMemory(): bigint
  totalSwap(): bigint
  freeSwap(): bigint
  usedSwap(): bigint
  uptime(): void
  bootTime(): bigint
  systemName(): string | null
  longOsVersion(): string | null
  hostName(): string | null
  kernelVersion(): string | null
  osVersion(): string | null
  distribution(): string
  loadAverage(): LoadAvg
  refreshComponentsList(): void
}

export declare function cpuFeatures(): CpuFeatures

export interface CpuFeatures {
  arch: string
  brand?: string
  family?: number
  model?: number
  steppingId?: number
  flags: CpuFeaturesFlags
}

export interface CpuFeaturesFlags {
  asimd: boolean
  pmull: boolean
  fp: boolean
  fp16: boolean
  sve: boolean
  crc: boolean
  lse: boolean
  lse2: boolean
  rdm: boolean
  rcpc: boolean
  rcpc2: boolean
  dotprod: boolean
  tme: boolean
  fhm: boolean
  dit: boolean
  flagm: boolean
  ssbs: boolean
  sb: boolean
  paca: boolean
  pacg: boolean
  dpb: boolean
  dpb2: boolean
  sve2: boolean
  sve2Aes: boolean
  sve2Sm4: boolean
  sve2Sha3: boolean
  sve2Bitperm: boolean
  frintts: boolean
  i8Mm: boolean
  f32Mm: boolean
  f64Mm: boolean
  bf16: boolean
  rand: boolean
  bti: boolean
  mte: boolean
  jsconv: boolean
  fcma: boolean
  aes: boolean
  sha2: boolean
  sha3: boolean
  sm4: boolean
}

/**
 * A Object representing system load average value.
 *
 * ```js
 * import { SysInfo } from '@napi-rs/sysinfo';
 * const s = new SysInfo();
 * const loadAvg = s.loadAverage();
 *
 * console.log(
 *   `one minute: ${loadAvg.one}%, five minutes: ${loadAvg.five}%, fifteen minutes: ${loadAvg.fifteen}%`,
 * )
 * ```
 */
export interface LoadAvg {
  /** Average load within one minute. */
  one: number
  /** Average load within five minutes. */
  five: number
  /** Average load within fifteen minutes. */
  fifteen: number
}
